### ISSUE TITLE
I can't unpack the files successfully

### ISSUE THREAD

**Issue by suraxiuxiu** [ZimM-LostPolygon/10TonsPakProcessor#1]
when i run .\10TonsPakProcessor -unpack someFileToUnpack.pak  on cmd，
i show error
Error while executing operation: System.IO.FileNotFoundException: can‘t find the file name“D:\yule\game\ns\hax\jydge\JYD\romfs\-unpack”。
file name:“D:\yule\game\ns\hax\jydge\JYD\romfs\-unpack”
   on System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   on System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   on System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   on TenTonsPakProcessor.Program.UnpackPak(String pakPath)
   on TenTonsPakProcessor.Program.Main(String[] args)
What shall I do?  （Machine Translation please forgive）

**Comment by ZimM-LostPolygon** [comment]
The error message says it all - `\JYD\romfs-unpack` file doesn't exists. What are you trying to do? Please specify a correct .pak file, `data.pak` for example.
