### ISSUE TITLE
Still doesn't work.

### ISSUE THREAD

**Issue by Shituation** [ZimM-LostPolygon/10TonsPakProcessor#4]
It says that unpacked files but the files are not anywhere.

**Comment by ZimM-LostPolygon** [comment]
That is not sufficient information to help you. What are you unpacking? How?

**Comment by Shituation** [comment]
Crimsonland.
-unpack data-windows.pak

![1](https://user-images.githubusercontent.com/43975882/222240899-6dc264be-8715-4a55-bc95-d53e00387546.jpg)

**Comment by ZimM-LostPolygon** [comment]
There's no errors, so it's definitely unpacking somewhere. The unpacked files will be in your current working directory.

**Comment by Shituation** [comment]
No, they are not. Is that the "help" ?
I mean... I wouldn't be creating an issue.

**Comment by ZimM-LostPolygon** [comment]
Well... Simply put, there's no other option. If it were to fail creating the file, it would crash or show an error, but it's happily unpacking somewhere. If you are not able to find the unpacked files, then I suggest making triple sure your working directory is actually what you think it is

**Comment by Shituation** [comment]
https://user-images.githubusercontent.com/43975882/222242466-9288eaf5-c06e-4447-8e85-cd8180d82db4.mp4

You don't know where your software unpacks the files? is it random?

**Comment by ZimM-LostPolygon** [comment]
Yup, your working directory is `C:\Users\PC`, so I would expect you now have quite a bit of Crimsonland stuff in your Windows profile folder 😅

**Comment by Shituation** [comment]
So it unpacks to the working dir of the CMD and not the app exe. I see. I will have to clean my profile now.
It would be less messy if you could add a path for unpacked files.

**Comment by ZimM-LostPolygon** [comment]
I agree that would be a nice to have addition, but that's still the default behavior of well-behaving console apps. If there's no output path specified, or no way to specify then, then expect it to operate on the working directory... The working directory isn't necessarily the .exe path
